package com.frisboo.corebanking.security.circuitbreaker.actuator

import com.frisboo.corebanking.security.circuitbreaker.config.AutoConfigurationCircuitBreaker
import com.frisboo.corebanking.security.circuitbreaker.config.CircuitBreakerProperties
import com.frisboo.corebanking.security.circuitbreaker.contract.CircuitBreakerRegistry
import org.springframework.boot.actuate.endpoint.annotation.Endpoint
import org.springframework.boot.autoconfigure.AutoConfigureAfter
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty
import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration


