kotlin.code.style=official
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx2g
org.gradle.parallel=true
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled

# Make warnings fail locally too
warningsAsErrors=true

# Try new language features earlier
kotlin.progressive=true
