/*
 * Copyright 2025 Frisboo Bank
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package com.frisboo.corebanking.core.domain.valueobjects

public enum class Countries(
    public val code: String,
    public val displayName: String,
) {
    // ========================================
    // ASIA PACIFIC (45 countries)
    // ========================================
    AF("AF", "Afghanistan"),
    AS("AS", "American Samoa"),
    AU("AU", "Australia"),
    BD("BD", "Bangladesh"),
    BN("BN", "Brunei"),
    BT("BT", "Bhutan"),
    CC("CC", "Cocos Islands"),
    CK("CK", "Cook Islands"),
    CN("CN", "China"),
    CX("CX", "Christmas Island"),
    FJ("FJ", "Fiji"),
    FM("FM", "Micronesia"),
    GU("GU", "Guam"),
    HK("HK", "Hong Kong"),
    ID("ID", "Indonesia"),
    IN("IN", "India"),
    JP("JP", "Japan"),
    KH("KH", "Cambodia"),
    KI("KI", "Kiribati"),
    KP("KP", "North Korea"),
    KR("KR", "South Korea"),
    KZ("KZ", "Kazakhstan"),
    LA("LA", "Laos"),
    LK("LK", "Sri Lanka"),
    MM("MM", "Myanmar"),
    MN("MN", "Mongolia"),
    MO("MO", "Macao"),
    MV("MV", "Maldives"),
    MY("MY", "Malaysia"),
    NP("NP", "Nepal"),
    NR("NR", "Nauru"),
    NU("NU", "Niue"),
    NZ("NZ", "New Zealand"),
    PF("PF", "French Polynesia"),
    PG("PG", "Papua New Guinea"),
    PH("PH", "Philippines"),
    PK("PK", "Pakistan"),
    PN("PN", "Pitcairn"),
    PW("PW", "Palau"),
    QA("QA", "Qatar"),
    SB("SB", "Solomon Islands"),
    SG("SG", "Singapore"),
    TH("TH", "Thailand"),
    TJ("TJ", "Tajikistan"),
    TK("TK", "Tokelau"),
    TL("TL", "Timor-Leste"),
    TM("TM", "Turkmenistan"),
    TV("TV", "Tuvalu"),
    TW("TW", "Taiwan"),
    UZ("UZ", "Uzbekistan"),
    VN("VN", "Vietnam"),
    VU("VU", "Vanuatu"),
    WS("WS", "Samoa"),

    // ========================================
    // EUROPE (49 countries)
    // ========================================
    AD("AD", "Andorra"),
    AL("AL", "Albania"),
    AM("AM", "Armenia"),
    AT("AT", "Austria"),
    AX("AX", "Åland Islands"),
    AZ("AZ", "Azerbaijan"),
    BA("BA", "Bosnia and Herzegovina"),
    BE("BE", "Belgium"),
    BG("BG", "Bulgaria"),
    BY("BY", "Belarus"),
    CH("CH", "Switzerland"),
    CZ("CZ", "Czech Republic"),
    DE("DE", "Germany"),
    DK("DK", "Denmark"),
    EE("EE", "Estonia"),
    ES("ES", "Spain"),
    FI("FI", "Finland"),
    FO("FO", "Faroe Islands"),
    FR("FR", "France"),
    GB("GB", "United Kingdom"),
    GE("GE", "Georgia"),
    GG("GG", "Guernsey"),
    GI("GI", "Gibraltar"),
    GR("GR", "Greece"),
    HR("HR", "Croatia"),
    HU("HU", "Hungary"),
    IE("IE", "Ireland"),
    IM("IM", "Isle of Man"),
    IS("IS", "Iceland"),
    IT("IT", "Italy"),
    JE("JE", "Jersey"),
    LI("LI", "Liechtenstein"),
    LT("LT", "Lithuania"),
    LU("LU", "Luxembourg"),
    LV("LV", "Latvia"),
    MC("MC", "Monaco"),
    MD("MD", "Moldova"),
    ME("ME", "Montenegro"),
    MK("MK", "North Macedonia"),
    MT("MT", "Malta"),
    NL("NL", "Netherlands"),
    NO("NO", "Norway"),
    PL("PL", "Poland"),
    PT("PT", "Portugal"),
    RO("RO", "Romania"),
    RS("RS", "Serbia"),
    RU("RU", "Russia"),
    SE("SE", "Sweden"),
    SI("SI", "Slovenia"),
    SJ("SJ", "Svalbard and Jan Mayen"),
    SK("SK", "Slovakia"),
    SM("SM", "San Marino"),
    TR("TR", "Turkey"),
    UA("UA", "Ukraine"),
    VA("VA", "Vatican City"),

    // ========================================
    // MIDDLE EAST (14 countries)
    // ========================================
    AE("AE", "United Arab Emirates"),
    BH("BH", "Bahrain"),
    CY("CY", "Cyprus"),
    EG("EG", "Egypt"),
    IL("IL", "Israel"),
    IQ("IQ", "Iraq"),
    IR("IR", "Iran"),
    JO("JO", "Jordan"),
    KW("KW", "Kuwait"),
    LB("LB", "Lebanon"),
    OM("OM", "Oman"),
    PS("PS", "Palestine"),
    SA("SA", "Saudi Arabia"),
    SY("SY", "Syria"),
    YE("YE", "Yemen"),

    // ========================================
    // AFRICA (54 countries)
    // ========================================
    AO("AO", "Angola"),
    BF("BF", "Burkina Faso"),
    BI("BI", "Burundi"),
    BJ("BJ", "Benin"),
    BW("BW", "Botswana"),
    CD("CD", "Democratic Republic of the Congo"),
    CF("CF", "Central African Republic"),
    CG("CG", "Republic of the Congo"),
    CI("CI", "Ivory Coast"),
    CM("CM", "Cameroon"),
    CV("CV", "Cape Verde"),
    DJ("DJ", "Djibouti"),
    DZ("DZ", "Algeria"),
    EH("EH", "Western Sahara"),
    ER("ER", "Eritrea"),
    ET("ET", "Ethiopia"),
    GA("GA", "Gabon"),
    GH("GH", "Ghana"),
    GM("GM", "Gambia"),
    GN("GN", "Guinea"),
    GQ("GQ", "Equatorial Guinea"),
    GW("GW", "Guinea-Bissau"),
    KE("KE", "Kenya"),
    KM("KM", "Comoros"),
    LR("LR", "Liberia"),
    LS("LS", "Lesotho"),
    LY("LY", "Libya"),
    MA("MA", "Morocco"),
    MG("MG", "Madagascar"),
    ML("ML", "Mali"),
    MR("MR", "Mauritania"),
    MU("MU", "Mauritius"),
    MW("MW", "Malawi"),
    MZ("MZ", "Mozambique"),
    NA("NA", "Namibia"),
    NE("NE", "Niger"),
    NG("NG", "Nigeria"),
    RE("RE", "Réunion"),
    RW("RW", "Rwanda"),
    SC("SC", "Seychelles"),
    SD("SD", "Sudan"),
    SH("SH", "Saint Helena"),
    SL("SL", "Sierra Leone"),
    SN("SN", "Senegal"),
    SO("SO", "Somalia"),
    SS("SS", "South Sudan"),
    ST("ST", "São Tomé and Príncipe"),
    SZ("SZ", "Eswatini"),
    TD("TD", "Chad"),
    TG("TG", "Togo"),
    TN("TN", "Tunisia"),
    TZ("TZ", "Tanzania"),
    UG("UG", "Uganda"),
    YT("YT", "Mayotte"),
    ZA("ZA", "South Africa"),
    ZM("ZM", "Zambia"),
    ZW("ZW", "Zimbabwe"),

    // ========================================
    // NORTH AMERICA (33 countries)
    // ========================================
    AG("AG", "Antigua and Barbuda"),
    AI("AI", "Anguilla"),
    AW("AW", "Aruba"),
    BB("BB", "Barbados"),
    BL("BL", "Saint Barthélemy"),
    BM("BM", "Bermuda"),
    BS("BS", "Bahamas"),
    BZ("BZ", "Belize"),
    CA("CA", "Canada"),
    CR("CR", "Costa Rica"),
    CU("CU", "Cuba"),
    DM("DM", "Dominica"),
    DO("DO", "Dominican Republic"),
    GD("GD", "Grenada"),
    GL("GL", "Greenland"),
    GP("GP", "Guadeloupe"),
    GT("GT", "Guatemala"),
    HN("HN", "Honduras"),
    HT("HT", "Haiti"),
    JM("JM", "Jamaica"),
    KN("KN", "Saint Kitts and Nevis"),
    LC("LC", "Saint Lucia"),
    MF("MF", "Saint Martin"),
    MQ("MQ", "Martinique"),
    MS("MS", "Montserrat"),
    MX("MX", "Mexico"),
    NI("NI", "Nicaragua"),
    PA("PA", "Panama"),
    PM("PM", "Saint Pierre and Miquelon"),
    PR("PR", "Puerto Rico"),
    SV("SV", "El Salvador"),
    TC("TC", "Turks and Caicos Islands"),
    TT("TT", "Trinidad and Tobago"),
    US("US", "United States"),
    VC("VC", "Saint Vincent and the Grenadines"),
    VG("VG", "British Virgin Islands"),
    VI("VI", "U.S. Virgin Islands"),

    // ========================================
    // SOUTH AMERICA (12 countries)
    // ========================================
    AR("AR", "Argentina"),
    BO("BO", "Bolivia"),
    BR("BR", "Brazil"),
    CL("CL", "Chile"),
    CO("CO", "Colombia"),
    EC("EC", "Ecuador"),
    FK("FK", "Falkland Islands"),
    GF("GF", "French Guiana"),
    GY("GY", "Guyana"),
    PE("PE", "Peru"),
    PY("PY", "Paraguay"),
    SR("SR", "Suriname"),
    UY("UY", "Uruguay"),
    VE("VE", "Venezuela"),
    ;

    // ========================================
    // LOOKUP HELPERS
    // ========================================
    public companion object {
        private val byCode: Map<String, Countries> = entries.associateBy { it.code.uppercase() }
        private val byName: Map<String, Countries> = entries.associateBy { it.displayName.uppercase() }

        public fun fromCode(code: String): Countries? = byCode[code.uppercase()]

        public fun fromName(name: String): Countries? = byName[name.uppercase()]

        // ========================================
        // REGIONAL GROUPS
        // ========================================
        public val asiaPacific: Set<Countries> =
            setOf(
                AF,
                AS,
                AU,
                BD,
                BN,
                BT,
                CC,
                CK,
                CN,
                CX,
                FJ,
                FM,
                GU,
                HK,
                ID,
                IN,
                JP,
                KH,
                KI,
                KP,
                KR,
                KZ,
                LA,
                LK,
                MM,
                MN,
                MO,
                MV,
                MY,
                NP,
                NR,
                NU,
                NZ,
                PF,
                PG,
                PH,
                PK,
                PN,
                PW,
                SB,
                SG,
                TH,
                TJ,
                TK,
                TL,
                TM,
                TV,
                TW,
                UZ,
                VN,
                VU,
                WS,
            )

        public val europe: Set<Countries> =
            setOf(
                AD,
                AL,
                AM,
                AT,
                AX,
                AZ,
                BA,
                BE,
                BG,
                BY,
                CH,
                CZ,
                DE,
                DK,
                EE,
                ES,
                FI,
                FO,
                FR,
                GB,
                GE,
                GG,
                GI,
                GR,
                HR,
                HU,
                IE,
                IM,
                IS,
                IT,
                JE,
                LI,
                LT,
                LU,
                LV,
                MC,
                MD,
                ME,
                MK,
                MT,
                NL,
                NO,
                PL,
                PT,
                RO,
                RS,
                RU,
                SE,
                SI,
                SJ,
                SK,
                SM,
                TR,
                UA,
                VA,
            )

        public val middleEast: Set<Countries> =
            setOf(
                AE,
                BH,
                CY,
                EG,
                IL,
                IQ,
                IR,
                JO,
                KW,
                LB,
                OM,
                PS,
                QA,
                SA,
                SY,
                YE,
            )

        public val africa: Set<Countries> =
            setOf(
                AO,
                BF,
                BI,
                BJ,
                BW,
                CD,
                CF,
                CG,
                CI,
                CM,
                CV,
                DJ,
                DZ,
                EH,
                ER,
                ET,
                GA,
                GH,
                GM,
                GN,
                GQ,
                GW,
                KE,
                KM,
                LR,
                LS,
                LY,
                MA,
                MG,
                ML,
                MR,
                MU,
                MW,
                MZ,
                NA,
                NE,
                NG,
                RE,
                RW,
                SC,
                SD,
                SH,
                SL,
                SN,
                SO,
                SS,
                ST,
                SZ,
                TD,
                TG,
                TN,
                TZ,
                UG,
                YT,
                ZA,
                ZM,
                ZW,
            )

        public val northAmerica: Set<Countries> =
            setOf(
                AG,
                AI,
                AW,
                BB,
                BL,
                BM,
                BS,
                BZ,
                CA,
                CR,
                CU,
                DM,
                DO,
                GD,
                GL,
                GP,
                GT,
                HN,
                HT,
                JM,
                KN,
                LC,
                MF,
                MQ,
                MS,
                MX,
                NI,
                PA,
                PM,
                PR,
                SV,
                TC,
                TT,
                US,
                VC,
                VG,
                VI,
            )

        public val southAmerica: Set<Countries> =
            setOf(
                AR,
                BO,
                BR,
                CL,
                CO,
                EC,
                FK,
                GF,
                GY,
                PE,
                PY,
                SR,
                UY,
                VE,
            )
    }
}
