/*
 * Copyright 2025 Frisboo Bank
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package com.frisboo.corebanking.resilience.ratelimiter.model

import com.frisboo.corebanking.resilience.ratelimiter.testutils.createRateLimiterConfigArb
import io.kotest.assertions.throwables.shouldNotThrow
import io.kotest.assertions.throwables.shouldThrow
import io.kotest.core.spec.style.StringSpec
import io.kotest.property.Arb
import io.kotest.property.arbitrary.int
import io.kotest.property.arbitrary.long
import io.kotest.property.checkAll
import kotlin.time.Duration
import kotlin.time.Duration.Companion.milliseconds
import kotlin.time.Duration.Companion.seconds

internal class RateLimiterConfigTest :
    StringSpec(
        {

            fun validBaseConfig() =
                RateLimiterConfig(
                    limitForPeriod = 50,
                    limitRefreshPeriod = 1.seconds,
                    timeoutDuration = 500.milliseconds,
                )

            "rejects limitForPeriod <= 0" {
                checkAll(Arb.int(-1_000, 0)) { bad ->
                    shouldThrow<IllegalArgumentException> {
                        validBaseConfig().copy(limitForPeriod = bad)
                    }
                }
            }

            "rejects non-positive limitRefreshPeriod" {
                checkAll(Arb.long(-1_000, 0)) { badMs ->
                    shouldThrow<IllegalArgumentException> {
                        validBaseConfig().copy(limitRefreshPeriod = badMs.milliseconds)
                    }
                }
            }

            "rejects negative timeoutDuration" {
                checkAll(Arb.long(-1_000, -1)) { badMs ->
                    shouldThrow<IllegalArgumentException> {
                        validBaseConfig().copy(timeoutDuration = badMs.milliseconds)
                    }
                }
            }

            "accepts zero timeoutDuration" {
                shouldNotThrow<IllegalArgumentException> {
                    validBaseConfig().copy(timeoutDuration = Duration.ZERO)
                }
            }

            "accepts any valid configuration generated by the arb" {
                checkAll(createRateLimiterConfigArb()) { config ->
                    shouldNotThrow<IllegalArgumentException> { config }
                }
            }

            "accepts large limitForPeriod" {
                shouldNotThrow<IllegalArgumentException> {
                    validBaseConfig().copy(limitForPeriod = 1_000_000)
                }
            }

            "accepts limitForPeriod of 1" {
                shouldNotThrow<IllegalArgumentException> {
                    validBaseConfig().copy(limitForPeriod = 1)
                }
            }
        },
    )
