/*
 * Copyright 2025 Frisboo Bank
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package com.frisboo.corebanking.http.domain.models

import java.net.URI

/**
 * Represents an HTTP error response returned by the API.
 *
 * @property status The HTTP status code associated with the error.
 * @property message A human-readable message describing the error.
 */
public data class HTTPErrorResponse(
    /**
     * A short, human-readable summary of the problem type.
     */
    val title: String,

    /**
     * The HTTP status code generated by the origin server for this occurrence of the problem.
     */
    val status: Int,

    /**
     * A URI reference that identifies the problem type.
     */
    val type: URI? = URI.create("about:blank"),

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    val detail: String? = null,

    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    val instance: URI? = null,

    /**
     * A unique identifier for tracking the error across systems.
     */
    val correlationId: String,

    /**
     * An application-specific error code.
     */
    val code: String,

    /**
     * A list of validation errors, if applicable.
     */
//    val errors: List<ValidationError>? = null,

    /**
     * A map of additional, application-specific information about the error.
     */
    val extensions: Map<String, Any?> = emptyMap(),
) {
    init {
        require(title.isNotBlank() && title.length <= 200) {
            "title must be 1..200 characters"
        }
        require(status in 400..599) {
            "status must be within 400..599"
        }
    }
}
